services:
  mysql-test:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tidy_admin_test
    ports:
      - '3309:3306'
    tmpfs:
      - /var/lib/mysql
